name: Weekly newsletter

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch: {}

jobs:
  run-weekly:
    runs-on: ubuntu-latest
    env:
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: python -m pip install -r requirements.txt
      - name: Run weekly task
        working-directory: .
        run: python scripts/weekly_task.py
